Add Characteristic Cycling Speed Cadence
FitnessKit/BluetoothMessageProtocol pull request #5
Opened 2020-10-18 17:57 UTC by joeblau

Add CharacteristicCyclingSpeedCadence to SIG

2020-10-23 14:06 UTC, khoogheem commented on Sources/BluetoothMessageProtocol/Characteristic/SIG/CharacteristicCyclingSpeedCadence.swift
> +    public enum PresentData {
I would rather see this as a actual Struct that is: Revolutions + lastEvent Time
and then have one var for wheel and one for crank

2020-10-23 14:06 UTC, khoogheem commented on Sources/BluetoothMessageProtocol/Characteristic/SIG/CharacteristicCyclingSpeedCadence.swift
> +
space

2020-10-23 14:06 UTC, khoogheem commented on Sources/BluetoothMessageProtocol/Characteristic/SIG/CharacteristicCyclingSpeedCadence.swift
> +
space

2020-10-23 14:06 UTC, khoogheem commented on Sources/BluetoothMessageProtocol/Characteristic/SIG/CharacteristicCyclingSpeedCadence.swift
> +/// BLE Alert Level Characteristic
fix

2020-10-23 14:08 UTC, khoogheem commented on Sources/BluetoothMessageProtocol/Characteristic/SIG/CharacteristicCyclingSpeedCadence.swift
> +//  File.swift
fix

2020-10-23 14:08 UTC, khoogheem requested changes
a few nits..

2020-10-23 14:08 UTC, khoogheem commented on Sources/BluetoothMessageProtocol/Characteristic/SIG/CharacteristicCyclingSpeedCadence.swift
> +
should have the terms

2021-03-14 05:25 UTC, joeblau commented
I accidentally deleted my other fork so I submitted a new PR (#7) with a live fork.

2021-03-14 05:25 UTC, closed without merging